version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: selters
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: selters
    ports:
      - "5432:5432"
