import Head from "next/head";
import Image from "next/image";
import styles from "./index.module.css";

import Header from "@/components/Header/Header";

import MenuLine from "@/components/MenuLIne/MenuLIne";
import { ListOfFilesResponse } from "@uploadcare/rest-client";

interface Props {
  loadImages: ListOfFilesResponse;
}

const Home = () => {
  return (
    <>
      <Head>
        <title>Karate Klub Selters</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Header />
        <h1 className={styles.title}>
          Selters
          <span className={styles.subHeading}>Karate Klub</span>
        </h1>
        <MenuLine />
        <Image
          className={styles.mainLogo}
          alt="Logo for the Menu"
          src="/logo-menu.svg"
          width={250}
          height={250}
        />
        <Image
          className={styles.mainBanner}
          alt="Logo for the Menu"
          src="/main-banner.svg"
          width={1000}
          height={200}
        />
        <div className={styles.columnsContainer}>
          <div>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Et magni
              unde iste impedit blanditiis provident. Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Et magni unde iste impedit
              blanditiis provident. Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Et magni unde iste impedit blanditiis provident.
            </p>
          </div>
          <div>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Et magni
              unde iste impedit blanditiis provident. Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Et magni unde iste impedit
              blanditiis provident. Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Et magni unde iste impedit blanditiis provident.
            </p>
          </div>
          <div>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Et magni
              unde iste impedit blanditiis provident. Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Et magni unde iste impedit
              blanditiis provident. Lorem ipsum dolor sit amet consectetur
              adipisicing elit. Et magni unde iste impedit blanditiis provident.
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
