import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import styles from "./index.module.css";

import Header from "@/components/Header/Header";
import { api } from "@/utils/api";

import { env } from "@/env.mjs";
import { useGetAllImages } from "@/features/imageHandling/hooks/imageHooks";
import {
  listOfFiles,
  ListOfFilesResponse,
  UploadcareSimpleAuthSchema,
} from "@uploadcare/rest-client";

interface Props {
  loadImages: ListOfFilesResponse;
}

const Home = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { images } = useGetAllImages();

  console.log("IMAGES FROM tRPC and custom HOOK", images);

  return (
    <>
      <Head>
        <title>Karate Klub Selters</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>T3</span> App
          </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>First Steps →</h3>
              <div className={styles.cardText}>
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Documentation →</h3>
              <div className={styles.cardText}>
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <div className={styles.showcaseContainer}>
            <p className={styles.showcaseText}>
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className={styles.authContainer}>
      <p className={styles.showcaseText}>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className={styles.loginButton}
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};

export async function getServerSideProps() {
  const uploadcareSimpleAuthSchema = new UploadcareSimpleAuthSchema({
    publicKey: env.UPLOAD_CARE_PUBLIC_KEY,
    secretKey: env.UPLOAD_CARE_SECRET_KEY,
  });

  const result = await listOfFiles(
    {},
    { authSchema: uploadcareSimpleAuthSchema }
  );

  return {
    props: { loadImages: result },
  };
}
